### ISSUE TITLE
Move to a new github organization?

### ISSUE THREAD

**Issue by jeremyf** [ndlib/presqt-ui#52]
In looking at the contributors, this does not appear to make sense as an NDLIB organization repository. Can a new organization be created for this repository?

**Comment by dbrower** [comment]
This repository is related to the other presqt repository. It is for the same grant, and uses the same (grant-paid) developer seats as the former. I don't understand why you think it should be moved.

/cc @nkmeyers

**Comment by jeremyf** [comment]
When I see repositories that don't have any Hesburgh Library contributors, I'm interested in the use-case and if it makes sense to be in the ndlib organization (instead of something like presqt-at-nd).

**Comment by jeremyf** [comment]
Based on the grant and work being done, as well as the other repositories regarding PresQT, this repository makes sense in ndlib. Thank you for the discussion.
